service: suraj-demo-serverless
provider:
    name: aws
    runtime: nodejs16.x
    region: ap-south-1
    iamRoleStatements:
     -  Effect: "Allow"
        Action:
        -   dynamodb:*
        Resource:
        -   arn:aws:dynamodb:ap-south-1:477748561388:table/GraphqlServerlessCRUD
  
functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
      - http:
            path: graphql
            method: post
            cors: true
      - http:
            path: graphql
            method: get
            cors: true
plugins:
  - serverless-webpack
  - serverless-offline
custom:
  webpack:
    includeModules: true


resources:
    Resources:
        GraphqlServerlessCRUD:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: GraphqlServerlessCRUD
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions:
                    -   AttributeName: id    
                        AttributeType : S
                KeySchema: 
                    -   AttributeName: id
                        KeyType: HASH
